#!/bin/bash -e

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null && pwd )"

ASSEMBLED_FILE=/tmp/$random$random.wasm

"$DIR/external/wat2wasm" "$1" -o "$ASSEMBLED_FILE"
"$DIR/external/wasm-interp" "$ASSEMBLED_FILE" --run-all-exports
rm "$ASSEMBLED_FILE"
